# Generated by Django 5.2.14 on 2026-05-27 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='message',
            name='delivery_status',
            field=models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('delivered', 'Delivered'), ('undelivered', 'Undelivered'), ('failed', 'Failed')], default='queued', max_length=20),
        ),
        migrations.AddField(
            model_name='message',
            name='error_message',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='provider_message_id',
            field=models.CharField(blank=True, db_index=True, max_length=255, null=True),
        ),
    ]
