# Generated by Django 5.2.14 on 2026-05-27 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0002_message_delivery_status_message_error_message_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='state',
            field=models.CharField(choices=[('NEW', 'New Conversation'), ('QUALIFYING', 'Qualifying Lead details'), ('WAITING_FOR_ADDRESS', 'Awaiting Address details'), ('WAITING_FOR_INSPECTION_TIME', 'Awaiting Preferred Inspection Time'), ('BOOKING_REQUESTED', 'Inspection Booking Requested'), ('HUMAN_HANDOFF', 'Escalated to Human Takeover'), ('CLOSED', 'Closed')], db_index=True, default='NEW', max_length=30),
        ),
    ]
