# Generated by Django 5.2.14 on 2026-05-27 17:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('conversations', '0003_conversation_state'),
    ]

    operations = [
        migrations.AddField(
            model_name='conversation',
            name='last_ai_confidence',
            field=models.FloatField(default=1.0),
        ),
    ]
