# Generated by Django 5.2.14 on 2026-05-27 17:47

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('businesses', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Lead',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(blank=True, default='', max_length=255)),
                ('phone', models.CharField(db_index=True, max_length=30)),
                ('email', models.EmailField(blank=True, default='', max_length=254)),
                ('address', models.CharField(blank=True, default='', max_length=500)),
                ('roof_issue', models.TextField(blank=True, default='')),
                ('urgency', models.CharField(choices=[('IMMEDIATE_LEAK', 'Immediate Active Leak'), ('ACTIVE_DAMAGE', 'Active Storm Damage'), ('STANDARD_ESTIMATE', 'Standard Replacement/Repair Estimate'), ('PLANNING', 'General Planning / Inquiry')], default='STANDARD_ESTIMATE', max_length=20)),
                ('priority_score', models.IntegerField(default=50)),
                ('source', models.CharField(choices=[('GOOGLE_ADS', 'Google Ads'), ('FACEBOOK', 'Facebook Ads'), ('WEBSITE', 'Website Widget'), ('MISSED_CALL', 'Missed Call SMS Auto-Text')], default='WEBSITE', max_length=20)),
                ('status', models.CharField(choices=[('NEW', 'New Lead'), ('QUALIFYING', 'Qualifying In-Progress'), ('QUALIFIED', 'Qualified'), ('BOOKED', 'Booked Inspection'), ('UNQUALIFIED', 'Unqualified'), ('ARCHIVED', 'Archived')], default='NEW', max_length=20)),
                ('preferred_inspection_time', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('business', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leads', to='businesses.business')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
