# Generated by Django 5.2.14 on 2026-05-27 17:50

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LeadActivity',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('activity_type', models.CharField(choices=[('missed_call', 'Missed Call Received'), ('sms_sent', 'SMS Message Sent'), ('sms_received', 'SMS Message Received'), ('ai_response', 'AI Autoreply Generated'), ('appointment_requested', 'Appointment Slot Requested')], max_length=30)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('lead', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activities', to='leads.lead')),
            ],
            options={
                'verbose_name_plural': 'Lead Activities',
                'ordering': ['-created_at'],
            },
        ),
    ]
